# --- ビルドステージ ---
FROM node:20-alpine AS builder

WORKDIR /app

COPY package.json package-lock.json* ./
RUN npm ci

COPY . .

ARG BACKEND_URL
ARG BACKEND_PORT
ARG PEER_URL

ENV BACKEND_URL=$BACKEND_URL
ENV BACKEND_PORT=$BACKEND_PORT
ENV PEER_URL=$PEER_URL

RUN npm run build

# --- 実行ステージ ---
FROM nginx:alpine
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]